POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVlOGRlYWI3MWZlNmFjM2FmZTNmMTE0MyIsImlhdCI6MTU4NjY4MjAyMH0.nBd_-zLgaOGIbxT8jx9ngCtjaI6mQSUJOUN19ogC0rU

{
  "title": "Blogi jolla on yksi kirjoittaja",
  "author": "String",
  "url": "http:s//",
  "likes": 1
}
